### ISSUE TITLE
Standardization of Multilingual Support

### ISSUE THREAD

**Issue by shigeya** [w3c/vc-wg-charter#19]
As I mentioned during the TPAC 2022 VC meeting two weeks ago, we need multilingual support, especially for Asian countries.

While some examples (even the first example) in the Verifiable Credential  1.1 spec show how you can encode multinational strings into a property value, there is a lack of discussion about this scheme.

Since these strings need to be content-integrity protected, externalizing translation mapping is not an option; multilingual support must be part of the Verifiable Credentials Data Model.

In Japan, we already observe difficulty in vaccination certificates since we need to use English for overseas purposes and Japanese for domestic purposes. Both the data model and the software support are in need. Thus, standardizing support in the Verifiable Credentials Data Model is necessary.

We understand this is a challenging topic, especially when looking at the data representation syntax point of view. But for the more general, international adoption, we need multilingual support without affecting single-lingual syntax.

I think including this work as part of Verifiable Credential 2.0 work is essential.

**Comment by shigeya** [comment]
I forgot to mention that I (of course) want to contribute. I'm thinking about how this work fits into the charter and looking forward to having discussions/comments.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-01-vcwg#section1-1) on 2021-12-01

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.1. Standardization of Multilingual Support (issue vc-wg-charter#19)

_See github issue [vc-wg-charter#19](https://github.com/w3c/vc-wg-charter/issues/19)._




**Brent Zundel:** Seems like there is support for this, how do we make sure this happens?.  

**Shigeya Suzuki:** I was not sure how to proceed w/ PR -- how do we fit this into the charter?.  
… I'll propose something in a PR..  

</details>

**Comment by kdenhartog** [comment]
I'm curious if the need for this extends beyond the support offered by JSON-LD today or if this is something that you're looking to get standardized among all of the different representations? Also worth asking, is the usage of JSON-LD's feature for this fall under your classification of "externalizing translation mapping"?

**Comment by shigeya** [comment]
@kdenhartog thanks for the comment.  Sorry for the late response.

Feature-wise, for the use-cases I saw, the language-indexing feature mentioned in [Language indexing](https://json-ld.org/spec/latest/json-ld/#language-indexing) of JSON-LD 1.1 is sufficient.

On "externalizing translation mapping."  it's different from the JSON-LD's feature I think. Let me describe what I'm thinking of.

Firstly, Let me describe how apps externalize translated texts outside of the binary code. For Unix-like systems and macOS, application programs code strings in a specific language (I assume it's usually in English), then, language mapping library such as [GNU gettext](https://www.gnu.org/software/gettext/) maps the string into a selected language on runtime using the selected mapping table. Developers prepare such mapping tables for each of the languages the application supports. For macOS, each application contains such mappings as compressed XML files in the `Contents/Resources` directories in the .app package file. Since this file is optional, the selection of language available to the app depends on the availability of the mapping tables.

By using a similar technique, we may prepare the VC in English while allowing translation. 

If the variation of strings in the VC is static and can be shared among multiple VCs, applying this externalization technique can be useful, but of course, there are multiple potential issues and concerns that need to be addressed if we externalize these mapping objects.

**Comment by kdenhartog** [comment]
Thanks for the reasoning behind this. I think I understand where you're coming from now and for the JSON-LD specific representations I think it's possible to achieve this without the external mapping technique you described. However, if we're going to handle this at the abstract data model layer than that's going to be a bit more complex from my read of things (and I believe that matches your assessment as well).

I'm inclined to say that this seems like a valuable feature we should be thinking about and can think of a few different ways to achieve it. If we can standardize on this though that would help to reduce the number of code paths that need to be supported for this.

I'm a +1 to adding this in scope of the new work.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-08-vcwg#section1-7) on 2021-12-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.7. Standardization of Multilingual Support (issue vc-wg-charter#19)

_See github issue [vc-wg-charter#19](https://github.com/w3c/vc-wg-charter/issues/19)._




**Brent Zundel:** Final issue for today is #19. Standardization of multilingual support..  
… There's a recent conversation..  
… Shigeya made some new comments..  
… It's still not exactly clear what he's looking for regarding changes to the charter..  

**Ivan Herman:** I scanned through what he wrote to try to understand it. He gave some answer there. I think the idea ... first of all is that what he says is JSON-LD is great and it works and there is no problem there. The example he has, for others who may not have ready it... if you take an environment on iOS/Android....  
… There are standard ways to handle localizations of applications where the translation of terms are not built into the system but are stored in some well-agreed place and the app can use that to translate and localize..  
… There seems to be some formats there and Shigeya is just asking to look into that mechanism and incorporate into VC. I'm not saying I understand all the technical details there but essentially making the translations of a VC instance and using some system features rather than build in what JSON-LD does..  

**Manu Sporny:** My read is the exact same, I think, as Ivan's. It's a super interesting way of solving the problem. My expectation is that it would result in the VC data model called like "translation file" and we'd have to figure out if we use content hashes there. I'd say that whole discussion falls into the VC 2.0 work..  
… We should discuss it. We have the ability to have the discussions because the 2.0 work is contemplating new features that people feel are needed in the ecosystem and this is one of those..  

**David Chadwick:** This is an issue we're already discussing in our company as well and it's timely. I wonder if we can put into the scope of the next WG to consider internationalization and maybe outside of the scope of JSON-LD.  

**Kevin Dean:** I'd very much like to see that, this is for everyone, not just the English-speaking world..  

**Charles Lehner:** I wonder if JSON-LD context files and framing could be helpful here, but I'm not sure how that would translate to JWT..  

**Ivan Herman:** Maybe to answer Charles, my feeling is that the answer is that it is very different. I think the idea is not to localize the terms we use within the VC in the vocab, whatever is in the context, but it's more whatever has effectual meaning should be localized when you display things..  
… It's more to do maybe with the user interface for the VC than the VC itself..  

> *Manu Sporny:* Agree with Ivan..

**Ivan Herman:** The only thing we should do at this point is to ask Shigeya to give us a very specific PR or comment into the charter text and that's it. I think we clearly agree that something like that is important..  
… He should help us formalize it..  

> *Charles Lehner:* thanks.

**Brent Zundel:** So it sounds like we need to make sure that Shigeya knows we are in support of these ideas and we are looking forward to a PR to the charter to bring it into scope..  

</details>

**Comment by shigeya** [comment]
(My apologies for not attending the last call. Part of my daytime work is currently adamant, and I can't stay up to very late)

**Comment by brentzundel** [comment]
> (My apologies for not attending the last call. Part of my daytime work is currently adamant, and I can't stay up to very late)

We recognize that our meeting times are extremely inconvenient for participants from your area and apologize for that. 
We hope that the time for tomorrow's meeting will be slightly less miserable for you and that you are able to join us, but are also open to adjusting our meeting times in your favor should that be needed for you regular attendance to be possible.

**Comment by shigeya** [comment]
@brentzundel Thanks for the heads-up. I will definitely attend the next call tomorrow.

I will try to issue a PR.
I also will prepare some initial conceptual examples (not part of the commits, of course).

**Comment by shigeya** [comment]
I want to propose two schemes for multilingual support for VC 2.0.

By using either one of the schemes, the developer may selectively display local languages.

# Embedding into VC

The first scheme is similar to the current [VC 1.1 Example 1](https://w3c.github.io/vc-data-model/#example-a-simple-example-of-a-verifiable-credential). 

There are no normative texts on expressing strings for each of the multiple languages corresponding to a single string. The spec needs such normative texts.

It is necessary to standardize this in the VC data model.

Example:
```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "http://example.edu/credentials/1872",
  "type": ["VerifiableCredential", "AlumniCredential"],
  "issuer": "https://example.edu/issuers/565049",
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "alumniOf": {
      "id": "did:example:c276e12ec21ebfeb1f712ebc6f1",
      "name": {"en": "Example University",
	           "fr": "Exemple d'Université"}
    }
  },
  "externalLanguageMapping": "http://example.edu/credentials/langmaps.json#HASH"
// snip
}

```


# Externalizing mapping texts with integrity protection

If you have more than a few languages and want flexibility, you may want to externalize mappings. For example,

- Express a VC in the primary language (maybe English)
- Create a mapping data object external to the VC, store it somewhere
- Link the object from VC. It is possible to share the object among multiple VCs
- For integrity protection, the mapping object's hash should be integrity protected part of the VC

A bonus of this scheme is, we can expect smaller VC.

The simplest way to store/link is, of course, the use of an URL. We probably want to apply Manu's Hashlink.  

Example:
```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "http://example.edu/credentials/1872",
  "type": ["VerifiableCredential", "AlumniCredential"],
  "issuer": "https://example.edu/issuers/565049",
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "alumniOf": {
      "id": "did:example:c276e12ec21ebfeb1f712ebc6f1",
      "name": {"*": "Example University"}
    }
  },
  "languageMapping": "http://example.edu/credentials/langmaps.json#HASH"
// snip
}
```

Key `*` used for primary mapping

Example for mapping object (only bare-bone):
```
{
  "originalLanguage": "en",
  "languagePriority": ["en", "fr"],
  "fr": {
	  "Example University" : "Exemple d'Université"
  }
}
```
or possibly:
```
{
  "originalLanguage": "en",
  "languagePriority": ["en", "fr"],
  "mappings": {
	  "Example University" : { "fr": "Exemple d'Université" }
  }
}
```

Note: I found some discussions on [GNU gettext](https://www.w3.org/TR/mlw-metadata-us-impl/#Using_ITS_2.0_with_GNU_gettext_utilities.2FPO_files) in a W3C document [Metadata for the Multilingual Web - Usage Scenarios and Implementations](https://www.w3.org/TR/mlw-metadata-us-impl/). This document does not include a discussion about integrity-protected translations.

# Work items

Thus, to include these two schemes, two work items are needed:
- For data model: Embed scheme and how to refer externalized mapping
- Data Model of the externalized mapping

PR #33 includes changes for these work items in mind.

**Comment by shigeya** [comment]
During the call, I mentioned property name translation might be useful too.

While writing discussions on that, I realized that it might be useful even for English, if there is a descriptive name of properties are available. I will check if there were past discussions related to this, then create a different issue for the discussion on descriptive name and translation.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-15-vcwg#section1-4) on 2021-12-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.4. Standardization of Multilingual Support (issue vc-wg-charter#19)

_See github issue [vc-wg-charter#19](https://github.com/w3c/vc-wg-charter/issues/19)._




**Brent Zundel:** One other issue to cover for this.  

**Shigeya Suzuki:** I posted examples yesterday for this and filed a PR for this and got feedback from Kyle and Manu.  
… my proposal has two schemes to do translation and I think now what I'm trying to do is understand it better.  
… the thing that I was wondering how to express new work items in the charter.  

_See github pull request [vc-wg-charter#33](https://github.com/w3c/vc-wg-charter/pull/33)._




**Shigeya Suzuki:** and I'm not sure if it's good now.  
… If certain citations we may want to have some sort of table like list to translate both the key and value.  
… and I wanted to get further feedback on this.  

**Kyle Den Hartog:** Just to comment on the specifics of whether this is adequate..  
… I think the text added to charter makes it good enough, and things you're discussing are things we can get feedback in WG. Good that you're getting jump start on this, when adding text to spec, that's where we can figure out what makes sense..  

**Brent Zundel:** any other comments, questions, concerns?.  
… Those were the VCWG draft charter issues.  
… we've got about 10 minutes left for the other parts of the agenda.  

</details>

**Comment by shigeya** [comment]
Merged. Closing.
