### ISSUE TITLE
External organizations - ISO/IEC JTC 1/SC 17/WG 10

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-wg-charter#20]
Why was ISO/IEC JTC 1/SC 17/WG 10 removed from the external organizations? It was in the vc-data-model 1.0 charter.

**Comment by brentzundel** [comment]
It was an oversight. I'm working on a PR to re-add them as an external organization.
Should specific mention be made also of the ISO group that described how to use mDL as a VC?

**Comment by brentzundel** [comment]
see PR #26

**Comment by Sakurann** [comment]
yes, it should also mention ISO/IEC JTC 1/SC 17/WG 4 since 23220-2 data model technical specification mentions VCs

**Comment by brentzundel** [comment]
> yes, it should also mention ISO/IEC JTC 1/SC 17/WG 4 since 23220-2 data model technical specification mentions VCs

this is done in [6ecdebf](https://github.com/w3c/vc-wg-charter/pull/26/commits/6ecdebf1f09ac31051eaac94710a569d16744651)

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-01-vcwg#section1-7) on 2021-12-01

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.7. External organizations - ISO/IEC JTC 1/SC 17/WG 10 (issue vc-wg-charter#20)

_See github issue [vc-wg-charter#20](https://github.com/w3c/vc-wg-charter/issues/20)._




**Brent Zundel:** The set of external organizations that we liaise with was missing, I raised a PR that adds two of them back specifically, and Kristina has noted another WG that is specifically at ISO working on mobile DL as VCs -- change my PR to add that one as well..  

> *Manu Sporny:* See [Verifiable Driver's Licenses and ISO-18013-5 (mDL)](https://lists.w3.org/Archives/Public/public-credentials/2021Nov/0105.html).

**Manu Sporny:** I would like to find a way to add that VC DL as a work item to the group. nothing normative, just a note.  
… it would help us talk about how these two disparate ecosystems can interop.  

**Brent Zundel:** would you be able to open a PR?.  

**Manu Sporny:** yes, I'll do that. Just wanted to bring it up..  

**David Chadwick:** With respect to the latter point, looked at VC -- specifying a proof format, don't mind if we limit it to the credential and contents of credential, but not go into specifying the proof format -- VC data model doesn't specify proof format..  

**Manu Sporny:** the test suite has multiple types of digital signatures, just to show that you can..  
… it's hard to demonstrate selective disclosure without actually having a proof that allows selective disclosure to happen..  
… so, because the re-charter will have proof formats in scope,.  
… I don't see how we can object to talking about proof formats..  

**David Chadwick:** the standard already has a Selective Disclosure mechanism based on JWTs.  
… where the value is hashed, and the whole thing is signed..  
… so if we go down that route, we could use the existing mDL selective disclosure mechanism..  
… There is a proof format already for mDL -- that's already there -- if we go down that route, and we use existing mDL selective disclosure mechanism, that would be ok, or a different one if we have one..  
… or even a different mechanism, if they have one.  

**Manu Sporny:** the thing that's confusing me is -- you said 'if we have a different mechanism'. And we have one of those, BBS+.  
… and you're saying it's fine to do that. But also, simultaneously, you seem to be saying "we can't talk about any other proof format, other than what's in the mDL".  
… and again, proof formats are specifically in scope, for the 2.0 charter.  
… so we're either talking about proof formats, or we're not.  

**David Chadwick:** your specific work on mDL specifies one single proof format.  

**Manu Sporny:** it does not..  
… that may be where the miscommunication is..  

**David Chadwick:** I read it as "the proof format must be BBS+".  

**Manu Sporny:** no, the interop report shows at least two different formats, and does not mandate any proof format.  

**David Chadwick:** no problem, I missed that..  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-08-vcwg#section1-1) on 2021-12-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.1. External organizations - ISO/IEC JTC 1/SC 17/WG 10 (issue vc-wg-charter#20)

_See github issue [vc-wg-charter#20](https://github.com/w3c/vc-wg-charter/issues/20)._




**Brent Zundel:** External orgs. This was addressed in PR #26 which I've merged after getting feedback on it..  

_See github pull request [vc-wg-charter#31](https://github.com/w3c/vc-wg-charter/pull/31)._




**Brent Zundel:** It adds the open badges, the ISO committee for the mDL, it also adds the ISO committed for other mDL work..  

**Manu Sporny:** A quick note. I raised [PR #31](https://github.com/w3c/vc-wg-charter/pull/31) to add ecosystem support for mDL..  
… We had, in the Credentials CG, we had an individual from the ISO WG do a presentation, Andrew Hughes. We also announced that we have an interoperability test suite for mDL..  
… That conversation has been kicked off, this PR adds a non-normative work item to work on VC data models and data guidance and uses mDL as an example. It basically says we may put out non-normative guidance that helps interop in general..  

**Brent Zundel:** Thank you, Manu..  
… Folks should check out that PR, it's very straightforward, it adds a line of potential deliverables there..  
… I guess the question with this issue #20 ... I was hoping to hear back from Kristina -- everything she said she wanted has now been put into the charter so I think we can close this..  
… Is anyone opposed to that?.  
… Not hearing any opposition, so I'll close the issue over the meeting once the notes are in on that..  

</details>
