### ISSUE TITLE
Fixing problems identified through using the 1.0 and 1.1 specs must be in scope

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-wg-charter#22]
Several problems have been identified when people tried to use the 1.0 specification.  Some of these are ambiguities, resulting in different interpretations by different implementers.  Some of them are conflicts between normative text.  All potentially reduce interoperability among implementations.  Fixing these problems needs to be explicitly within scope, even in cases where the fix involves changing normative requirements relative to the previous specifications.

Please make fixing problems present in the earlier specifications explicitly within scope.

**Comment by brentzundel** [comment]
It feels like this may already be addressed with the in scope statement: `Data models for credentials, presentations, and proofs` combined with the description of the Verifiable Credentials Data Model 2.0 deliverable: `It will replace the current VC Data Model 1.0 Recommendation.`

But I would be happy to review a PR that suggests additional text.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-01-vcwg#section1-5) on 2021-12-01

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.5. Fixing problems identified through using the 1.0 and 1.1 specs must be in scope (issue vc-wg-charter#22)

_See github issue [vc-wg-charter#22](https://github.com/w3c/vc-wg-charter/issues/22)._




**Brent Zundel:** I don't disagree with this, but my response here was that we have in scope -- data models are in scope and talk about 2.0 deliverable being replacement for previous versions... feels like it's in scope in spirit. Do we need to be explicit about this?.  

**Manu Sporny:** it would be very weird for a WG to say "we're not going to fix the problems with the spec".  
… so, my read is the same as yours, brent. That's what new versions are /for/ - to fix the problems with previous versions..  
… so, that's already in scope.  

**Brent Zundel:** That was my read as well..  
… I'm not opposed to it, if we have to, fine -- we can say we'll address errors in previous versions -- of course we're going to do that..  

**Ted Thibodeau Jr.:** I agree that it'll be unnecessary, but it'll remove mike's objections..  
… We may also produce errata updates to 1.0 and 1.1..  

**Brent Zundel:** ok, I'll assign myself..  

**Gregory Natran:** Just wanted to say, looking at context of it -- he just wants an explicit mention in scope, seems to be only concern -- explicit marker that says we'll look at specific problems..  

**Ted Thibodeau Jr.:** Might be helpful to get him to enumerate the things he wants..  

**Joe Andrieu:** My concern is I think this is an anchor for him to say "these 5 things that are wrong need to be fixed" -- that creates debate/arguments rather than moving forward..  
… I wouldn't mind a neutral statement, improve 1.x -- but I think Mike's trying to anchor specific fixes that he wants the charter to say "this will be resolved"..  

**David Chadwick:** Mike is in the OpenID Connect group, he's aware of the JWT problems -- the inconsistencies, he might be implicitly referring to that. I wouldn't look deeper into this than what it appears to be on the surface. It is a genuine request to fix these problems..  

</details>

**Comment by brentzundel** [comment]
we believe this has been addressed by #29, closing

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-08-vcwg#section1-6) on 2021-12-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.6. Fixing problems identified through using the 1.0 and 1.1 specs must be in scope (issue vc-wg-charter#22)

_See github issue [vc-wg-charter#22](https://github.com/w3c/vc-wg-charter/issues/22)._




**Brent Zundel:** I created a PR and merged it. It adds a single line about adding errata to make that in scope..  
… I assert #22 can be closed. Any objection?.  

> *Manu Sporny:* +1, agree the PR fixed the issue..

**Brent Zundel:** Not hearing objections, only support..  
… Closing it..  

</details>

**Comment by brentzundel** [comment]
Reopening at request of @selfissued
