### ISSUE TITLE
fix the link to the first charter of the Verifiable Credentials Data Model 1.0

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-wg-charter#23]
The currently provided link seems broken.
> Other Charter: https://www.w3.org/2017/vc/charter.html

I think it should be https://www.w3.org/2017/vc/WG/charter.html

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-01-vcwg#section1-2) on 2021-12-01

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.2. fix the link to the first charter of the Verifiable Credentials Data Model 1.0 (issue vc-wg-charter#23)

_See github issue [vc-wg-charter#23](https://github.com/w3c/vc-wg-charter/issues/23)._




**Brent Zundel:** The link needs to be fixed, there is a PR for that -- this has been addressed by a PR..  

</details>
