### ISSUE TITLE
Protocols and APIs should remain out of scope

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-wg-charter#24]
The charter at https://www.w3.org/2017/vc/WG/charter.html states that APIs and protocols for using the Verifiable Credentials Data Model is out of scope.  Yet the new charter adds possible non-normative deliverables such as "Storage and Sharing of Verifiable Credentials" and "An API for Verifiable Credential Exchange", which appear to creep into that territory.  The working group should focus on creating a practical and useful data model, while leaving choices of platform APIs and use in communication protocols to those building and deploying systems using the data model.

Please explicitly state that protocol and API work are out of scope and remove possible deliverables that infringe on these areas.

**Comment by OR13** [comment]
I agree the data model is the first priority, but I question if keeping protocols out of scope will prevent real interoperability...

Regarding credential exchange protocols, we have a growing ecosystem of mostly not interoperable protocols... A short list of them:

- DIDComm v2
- OIDC
- OIDC Presentation Exchange?
- WACI Presentation Exchange
- W3C CCG VC API
- Credential Handler API

Obviously we can't work on OIDC in the W3C, but not being able to talk about it might make interop harder to achieve.

And the charter will be trivial to attack if protocol interop is out of scope:

"See, you don't have enough interop, you just defined data models, you need protocols for practical interop"

We saw this with DID Core... a JSON data model was not enough, we needed to define resolution better.

I share the concern regarding charter scope creep, but I am also concerned about fixing the charter scope too narrowly, and then seeing formal objections or "near objections" regarding interoperability, when our charter may not allow us to address those concerns.

I think we need to be able to talk about protocols in order to do a good job, but I am not sure we need to do so normatively.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-01-vcwg#section1-4) on 2021-12-01

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.4. Protocols and APIs should remain out of scope (issue vc-wg-charter#24)

_See github issue [vc-wg-charter#24](https://github.com/w3c/vc-wg-charter/issues/24)._




**Brent Zundel:** Mike has expressed his concerns, Orie has responded, anyone else want to comment?.  

**Manu Sporny:** we're not saying we're gonna do normative things here.  
… but we are absolutely incubating a VC API spec.  
… if one of the things we want to do is demonstrate an end-to-end ecosystem, the VC API could get us there pretty quickly.  
… multiple people are implementing, we're demonstrating interop around mDL, etc..  
… it's a useful thing to bring into the conversation, without saying we're going to standardize it.  
… so that's the reason to have it in scope -- the work /is/ happening..  
… and we'll get a lot of questions "how do you know this VC data model works, interops"? And one of our answers could be -- well, we have all these interop tests.  

**Phil Archer:** Trying to look into Mike's comment -- 2017 charter says things are out of scope... we're talking about the new charter... it was out of scope, but it's no longer out of scope, don't see what the problem is..  

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-08-vcwg#section1-3) on 2021-12-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.3. Protocols and APIs should remain out of scope (issue vc-wg-charter#24)

_See github issue [vc-wg-charter#24](https://github.com/w3c/vc-wg-charter/issues/24)._




**Brent Zundel:** We talked about this issue during our last meeting, Orie made some comments, still no response from Mike Jones. Any recommendations on how to move this issue forward?.  

**Manu Sporny:** I think we should close the issue. People want to talk about this, work is proceeding, Mike needs to make the case for why the non-normative version of this needs to be out of scope, why we can't talk about it at all. It's a strange ask..  

> *Manu Sporny:* +1 to pending close, we need a response..

**Brent Zundel:** We could put a pending close label on it and ping Mike Jones and see if he can respond to the feedback and make his case. Any opposition to that?.  

**Dave Longley:** +1 to that approach..  

**Brent Zundel:** If we still haven't heard from Mike the next time we meet we can close it..  

</details>

**Comment by brentzundel** [comment]
no response since marked pending close, closing.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-15-vcwg#section1-1) on 2021-12-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.1. Protocols and APIs should remain out of scope (issue vc-wg-charter#24)

_See github issue [vc-wg-charter#24](https://github.com/w3c/vc-wg-charter/issues/24)._




**Brent Zundel:** first issue is number 24.  
… last time we said we'd close it so I move to close the issue any opposed?.  
… none heard going to close this one.  

> *David Chadwick:* I did tell Mike last week about this.

</details>

**Comment by brentzundel** [comment]
Reopening at request of @selfissued

**Comment by OR13** [comment]
I think we should move `identifier` -> `publicKey` in scope, otherwise everyone will invent their own way of reinventing `dereferencing documentLoaders`

**Comment by Sakurann** [comment]
Do you mean mandating identifiers in VCs to be tied to a public key in some manner? ie identifier being referenceable to a pubKey or being a PubKey itself?

**Comment by iherman** [comment]
> I think we should move `identifier` -> `publicKey` in scope, otherwise everyone will invent their own way of reinventing `dereferencing documentLoaders`

@OR13 is this related to the current issue (API-s) or is it a comment on the spec itself (e.g., [§4.2](https://www.w3.org/TR/vc-data-model/#identifiers))? Sorry if I miss something obvious.

**Comment by OR13** [comment]
Lets look at a JWT header:

```
{
  "alg": "EdDSA",
  "kid": "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn#z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn"
}
```

1. If `kid` is absent, how do i lookup the key that this VC was signed with (kid is optional per the spec).

2. Assume `kid` is required, how do I get to a key that signed this JWS?

```
{
  "@context": [
    "https://www.w3.org/ns/did/v1",
    "https://w3id.org/security/suites/jws-2020/v1"
  ],
  "id": "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn",
  "verificationMethod": [
    {
      "id": "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn#z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn",
      "type": "JsonWebKey2020",
      "controller": "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn",
      "publicKeyJwk": {
        "kty": "OKP",
        "crv": "Ed25519",
        "x": "0-e2i2_Ua1S5HbTYnVB0lj2Z2ytXu2-tYmDFf8f5NjU"
      }
    }
  ],
  "assertionMethod": [
   "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn#z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn"
  ],
}
```

==>

```
{
      "id": "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn#z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn",
      "type": "JsonWebKey2020",
      "controller": "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn",
      "publicKeyJwk": {
        "kty": "OKP",
        "crv": "Ed25519",
        "x": "0-e2i2_Ua1S5HbTYnVB0lj2Z2ytXu2-tYmDFf8f5NjU"
      }
    }
```

==>

```
{
        "kty": "OKP",
        "crv": "Ed25519",
        "x": "0-e2i2_Ua1S5HbTYnVB0lj2Z2ytXu2-tYmDFf8f5NjU"
      }
```

But what happens if the key turns out to be `publicKeyMultibase` or some other representation?

Then it needs to be converted to JWK, or used with an implementation that produces or consumes JWS from keys that are not JWKs.

In short, its probably not good enough to just say these are identifiers.... it would be better to at least informative explain the objects you need to get from them (such as controller documents with verification methods inside them)... etc.

one solution would be to define the following "APIs":


```
didResolver = (didUrl = proof.verificationMethod || JWS.header.kid ) => didDocument 
publicKeyResolver = (didDocument, proof.verificationMethod || JWS.header.kid ) = > JWK 
```
or 

```
documentLoader = (proof.verificationMethod || JWS.header.kid) => VerificationMethod
publicKeyResolver = (VerificationMethod, proof.verificationMethod || JWS.header.kid ) = > JWK 
```

or 

```
publicKeyResolver = (proof.verificationMethod || JWS.header.kid ) => JWK 
```

I don't think assuming folks will solve these problems the same way will improve VC interop. 
I think we should try and be more explicit and provide more examples.

**Comment by OR13** [comment]
Related issue: https://github.com/w3c/vc-data-model/issues/863

**Comment by OR13** [comment]
Could be discussed in depth in V2 implementation guide.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-01-26-vcwg#section7-5) on 2022-01-26

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.5. Protocols and APIs should remain out of scope (issue vc-wg-charter#24)

_See github issue [vc-wg-charter#24](https://github.com/w3c/vc-wg-charter/issues/24)._



_See github pull request [vc-wg-charter#43](https://github.com/w3c/vc-wg-charter/pull/43)._




**Brent Zundel:** Issue 24. Originally raised by Mike, before he was even in the group. Recently had more conversation. Opening up the floor.  
… Mike, would you like to introduce the issue?.  

**Michael Jones:** Thank you. The point was made on the issue that there are a lot of protocols using the spec, which is great, that's a form of adoption, that's happened without us doing any of the protocols..  
… I think it would overload us and present us with more interop challenges if we are defining protocols..  
… But fine to talk about how choices in the data model may affect protocols..  
… Consider protocol considerations in scope, but I don't think it should be our job to pick winners among protocols..  
… So should remain out of scope, like it was for v1..  

**Orie Steele:** I agree with everything Mike just said.  
… One area of VCDM v1 where we experienced a lot of pain, regarding the JWT implementation.  
… We don't have a great way of going from the identifier to a key.  
… With the URL to URI change, same thing.  
… I know how to resolve URL, but not URI. Destroying interoperability. I agree with them, we have to be careful....  
… If we say there is an identifier and something behind it, we should be careful not to hand-wave that could lead to non-interoperability.  
… Maybe it doesn't fall into what this group considers a protocol. Apologies if it's not right place.  

**Michael Prorock:** Quick option, having a note similar to an implementation guide, etc., that if you want to exchange this over REST, you might want to use this... Maybe one way to approach it, I think in line with Mike Jones's comment.  

**Michael Jones:** I agree.  

**Kyle Den Hartog:** General understanding was to leave this non-normative..  
… I think the current text allows that to happen, and allows us to talk about the impact, and discuss it with other groups..  

**Brent Zundel:** Thank you all. Please continue the conversation in the [PR](https://github.com/w3c/vc-wg-charter/pull/43).  
… Welcome to everyone new here..  
… Next week meeting same time. Will update calendar. Thanks all.  

**Michael Jones:** Thank you for welcoming us..  

---

</details>

**Comment by OR13** [comment]
I prefer for us to add references to:

- https://openid.net/specs/openid-connect-4-verifiable-presentations-1_0.html
- https://openid.net/specs/openid-connect-4-verifiable-credential-issuance-1_0.html

And allow for the non normative discussions regarding such work items explicitly.

**Comment by mprorock** [comment]
> I prefer for us to add references to:
> 
> * https://openid.net/specs/openid-connect-4-verifiable-presentations-1_0.html
> * https://openid.net/specs/openid-connect-4-verifiable-credential-issuance-1_0.html
> 
> And allow for the non normative discussions regarding such work items explicitly.

this seems like a sane path that balances options for the WG to explore multiple paths as appropriate

**Comment by jandrieu** [comment]
After this was re-opened, I didn't understand the shift to discussion of JWKs and keys.

@OR13 said
> I think we should move identifier -> publicKey in scope, otherwise everyone will invent their own way of reinventing dereferencing documentLoaders

What does this have to do with whether or not protocols and APIs should remain out of scope?

It seems to me that ensuring that different protocols are supportable by the spec is important to everyone involved in this work. If it's important to support more than one protocol, we need to be able to discuss how we do that. If the goal were to support one and only one protocol, then it's even more important to have protocols and APIs in spec.

That said, it seems to me extensibility is the right option for inclusivity. Which means discussing but not necessarily defining such protocols. So leaving the definition of protocols out of normative scope seems appropriate.

However, if we can't even discuss protocols and APIs, I don't see how we can even understand whether or not the data model has what it needs to support any particular protocol. That feels like an impossible restriction on a collaborative process.

@selfissued Given the divergence into JWK discussions, can you clarify what you mean by protocols and APIs being out of scope and how that would improve the VCWG work?

**Comment by Sakurann** [comment]
@jandrieu discussion in PR #43 should give you more context. 

Short summary would be:
We seemed to have agreed that normative work on protocols/APIs is out of scope of this WG.
We are still discussing if non-normative work on protocols/APIs is in scope.

**Comment by jandrieu** [comment]
How to use VCs with any given protocol or API seems like an obvious part of an implementation guide, which could easily be broken into multiple NOTES as appropriate.

I don't understand the push back against non-normative work that explains how to use VCs in a particular context. If the WG can't even publish a NOTE about using VCs in particular ways, it would be so hamstrung as to make the work purely academic. If we want adoption, we should proactively support as many publications as are useful to help people apply the data model in different situations.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-02-02-vcwg#section5-2) on 2022-02-02

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.2. Protocols and APIs should remain out of scope (issue vc-wg-charter#24)

_See github issue [vc-wg-charter#24](https://github.com/w3c/vc-wg-charter/issues/24)._




**Brent Zundel:** Orie, if there is further refinement needed, we'd like to see a PR.  

> *Michael Prorock:* two PRs.

_See github pull request [vc-wg-charter#43](https://github.com/w3c/vc-wg-charter/pull/43)._




**Brent Zundel:** This issue (and PR) has received quite a lot of attention lately..  

_See github pull request [vc-wg-charter#66](https://github.com/w3c/vc-wg-charter/pull/66)._




**Brent Zundel:** MikeJ, can you give us a status update?.  

**Michael Jones:** This has been an active discussion, which is great... in summary, we do have consensus to not do normative protocol or API work..  
… There is a discussion on whether discussion on non-normative APIs and protocols should be in scope or not..  
… There is another thing we have consensus on, which is parenthetical remark in PR, discussion of implications of protocol usage needs to be in scope..  
… I had a private conversation about "interlinking" adding audience to jwts and connect protocol said how to use it. If we didn't have audience, we couldn't use it in the protocol..  

> *Orie Steele:* `kid` being pretty important for use in protocols... and disastrously not commented on in the V1 data model..

**Michael Jones:** There is an interplay where working on both can be helpful. That said, specifying non-normative API/deliverables would be a distraction. I did hear from Manu that WG has good track record of keeping their focus. We might also want to look at MikeP's PR..  

> *Michael Prorock:* [https://github.com/w3c/vc-wg-charter/pull/66](https://github.com/w3c/vc-wg-charter/pull/66) - ensures we don't touch on that stuff from a normative standpoint.

**Michael Jones:** His PR does says not to do normative API work, removes normative API deliverable, but then adds a bunch of other stuff..  

> *Orie Steele:* still not a day lol :).

**Michael Jones:** Orie said things couldn't be done in a day, but that could be a path to be done soon..  

> *Orie Steele:* I would be in favor of pairing down the non normatively deliverables even further..

> *Juan Caballero:* +1 to kyle, i can feel this confusion in my bones.

**Kyle Den Hartog:** I saw MikeP's PR -- agree with that direction. One of the most difficult is that people don't understand which protocols should be used when/where. This is the non-normative aspect that would be useful. One of the things that VC API comes into play is because it's a CCG work item, having it move to NOTE gives it a home and can point to it more easily..  
… OpenID/DIDComm are viewed as protocols that are accepted and widely usable, non-normative language -- we expect how protocols align to each other w/o having to set any specifics on what market must be doing. Set guidance on how market forms as multiple protocols exist..  

**Michael Prorock:** I wanted to clarify on the PR, MikeJ and Kyle got it well -- we clarify that we don't want to do normative protocol work, but from non-normative side, we don't want to box ourselves from talking about guidance to provide, critical from adoption and messaging standpoint. That's why I want to include those non-normative protocol items..  
… We don't want to limit ourselves, we need to allow WG to decide how much to allow in -- we are enabled to discuss stuff, talk about OIDC, how systems echange in API context, those are important things to provide developer context..  

**Orie Steele:** I agree with MikeP, as much as we want to get charter out to AC -- there are other things important, data model work here, w/o protocol to move things around is terrible and useless. We want to drive attention/traffic/support to where that work is happening. I need that work to be done sooner than I need the v2 charter sent to AC mailing list. We need those OpenID Connect drafts to be further along. We need a standard for moving that data model around. we won't be doing that work here, we want people to contribute, use what they have, be supportive of OIDC, IETF, etc..  

**Manu Sporny:** We do have consensus on not doing protocol work in a normative fashion. That's true. There's a corollary to that, which is -- as long as we can do work around describing protocols and how developers use them and all the things Mike Prorock and Orie have been outlining..  
… As long as we can do that in the group and that does include talking about the VC-API..  

> *Joe Andrieu:* +1 for publishing how to use external protocols with the VC Data Model.

**Manu Sporny:** We do not have consensus on not talking about protocol at all. What we don't have consensus on is not being able to talk about the VC-API or publishing it as a note..  
… A number of members in the group want to work on that non-normatively..  

> *Joe Andrieu:* Sounds like an implementation guide, which has always been an expectation for WGs to publish such items as non-normative NOTEs.

> *Orie Steele:* Use the "approve" and "request changes" feature.... make it easy for the chairs..

**Manu Sporny:** We should go forward with those things we have consensus on, but we should not overlook on the statements from Mike Prorock's PR... the only objector, I believe, is Mike Jones -- on the non-normative items from Mike Prorock. There's a fairly large group of people that want to be able to talk about this non-normatively and publish NOTEs..  
… I want to know if there's anyone else in the group other than Mike Jones that think non-normative work including NOTEs should be out of scope..  

> *Kristina Yasuda:* I think Tony made a comment it is also an IPR issue.

> *Orie Steele:* yes, and I don't agree with Tony :).

> *Kristina Yasuda:* saying protocols/APIs are in-scope normatively would have IPR implications for those joining if I understood correctly.

> *Brent Zundel:* non-normative discussion or specification of protocols or APIs has no bearing on IPR commitments.

**Michael Jones:** To Manu's point, he said that there are those that don't want us to talk about protocols at all -- I don't know who those people are. Using the audience example, data structure and protocol, important to understand relationship between the two. There is substantial objection to specifying protocols/APIs in this group. Fine to reference specs/discussions elsewhere, but there is a bright line between specifying protocol and just talking abut protocol work happening elsewhere..  
… We don't need to do protocol work, picking winners..  

> *Orie Steele:* I think this position is harmful..

**Michael Jones:** We defined JWTs w/o protocols, we knew they would use it, some of them in OAuth, data formats stands by itself and is used by all kinds of things, secured caller ID, which I never imagined, but that's great..  

> *Orie Steele:* everything that is being said right now is why we need to be allowed to comment on this in WG Notes..

> *Kevin Dean:* If a protocol is to be standardized, it should be done separately..

**Kyle Den Hartog:** Rhetorical question -- do we expect that the discussion of how data model is moved along many different protocols that we should be able to speak about wrt. parehtentical. If I issue VC around OpenID Connect, but want to present via VC API/DIDComm, if there are implications, how are we able to discuss those sorts of things w/o documents? CCG is considered referenceable, but is that good enough?.  

> *Michael Prorock:* +1 kdenhartog.

**Michael Jones:** We can talk about anything we want..  

> *Juan Caballero:* ^^.

> *Orie Steele:* there is a big difference between "discussions" and "blocking working group notes from being in scope for the charter"..

> *Michael Prorock:* +1 joe.

**Joe Andrieu:** I don't understand pushback against non-normative documents..  

> *Juan Caballero:* whether a NOTE somehow based on or taking as input document CCG can be one ingredient in the impl guide.

> *Juan Caballero:* feels to me the technicality under discussion.

> *Kristina Yasuda:* [https://github.com/w3c/vc-wg-charter/pull/43#issuecomment-1020826349](https://github.com/w3c/vc-wg-charter/pull/43#issuecomment-1020826349).

> *Kristina Yasuda:* we can non-normatively mention anything without saying so in the charter. fyi.

**Brent Zundel:** The question comes down to -- explicitly list intended non-normative notes that should be published concerning APIs/protocols. That's the remaining question/disagreement..  
… Thanks all for discussion, please continue discussion in issue tracker and PRs. Look forward to chatting next week..  

---

</details>

**Comment by brentzundel** [comment]
I believe that concrete changes have been made to the charter which address this issue. I am marking it `pending close` and will close in 7 days if no one objects.

@selfissued do you agree?

**Comment by selfissued** [comment]
I agree that the working group has addressed the intent of this issue.
