### ISSUE TITLE
Use of unclear term "specific style of supporting infrastructure"

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-wg-charter#25]
The draft charter says that "The development of any specific style of supporting infrastructure for a verifiable credentials ecosystem" is out of scope.  However, at least this reader has little to no idea what the term "specific style of supporting infrastructure" is referring to.

If this means that protocols and APIs are out of scope, I agree with it (as discussed in issue #24 ).  If that's what you mean, please be more explicit.  If you mean something else, please reword this such that most people will have a common understanding of the intended meaning.

**Comment by brentzundel** [comment]
I've added a small attempt at clarification in PR #28

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-01-vcwg#section1-6) on 2021-12-01

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.6. Use of unclear term "specific style of supporting infrastructure" (issue vc-wg-charter#25)

_See github issue [vc-wg-charter#25](https://github.com/w3c/vc-wg-charter/issues/25)._




_See github pull request [vc-wg-charter#28](https://github.com/w3c/vc-wg-charter/pull/28)._




**Brent Zundel:** I raised a PR that adds 3 words to the charter to explicitly say "such as a DLT", that was the intent of this out of scope..  
… I think it's been addressed, we'll have to wait to hear from Mike..  

**Ted Thibodeau Jr.:** Similar to the other one, the text here does not read to me as if mandating X -- if this line came out of the old charter, "we're not developing APIs" ... but this time we might, this line would make it so, no, we can't..  
… We might want to change to "The mandate of any".  

</details>

**Comment by brentzundel** [comment]
we believe this has been addressed by #28, closing.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-08-vcwg#section1-4) on 2021-12-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.4. Use of unclear term "specific style of supporting infrastructure" (issue vc-wg-charter#25)

_See github issue [vc-wg-charter#25](https://github.com/w3c/vc-wg-charter/issues/25)._




**Brent Zundel:** Issue #25 is about the specific style of supporting infrastructure. I altered my PR so that it brought in Ted's suggestions. I pulled the PR in after getting that feedback. So now the charter says it's out of scope for us to mandate to any specific style of infrastructure as a DLT..  

**Manu Sporny:** +1 to the change. It makes it very specific what we're talking about there..  
… We may want to spell out DLT or link to it because people may not know what it means, but great job..  

**Brent Zundel:** I will go ahead and say we believe this has been addressed and close the issue. Any opposition?.  
… Hearing none..  

</details>
