### ISSUE TITLE
Multilingual support for selecting a image file

### ISSUE THREAD

**Issue by shigeya** [w3c/vc-wg-charter#38]
I found use cases that selectively refer to image files that include strings in different languages as part of the images.

A change to this text in the charter is necessary:

> Extensions for binding multilingual strings to GNU gettext-like localization files

I couldn't immediately come up with a PR.
If there is any suggestion for change, please provide it.

**Comment by msporny** [comment]
This was addressed by https://github.com/w3c/vc-wg-charter/pull/33.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-01-12-vcwg#section2-2) on 2022-01-12

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.2. Multilingual support for selecting a image file (issue vc-wg-charter#38)

_See github issue [vc-wg-charter#38](https://github.com/w3c/vc-wg-charter/issues/38)._




**Shigeya Suzuki:** Sometimes we need to select from multiple image files to handle multi lingual text. Images may contain text inside images..  
… This is different from how multilingual text is handled.  
… I was thinking about opening a PR, but I could not find a good way to disclose that in a simple text.  

**Brent Zundel:** Manu posted a comment.  

**Manu Sporny:** But I was wrong.  

**Brent Zundel:** Any suggestions for shigeya how to address this?.  

**Manu Sporny:** We should reach out to Internationalization folks. We might want to ask them. Nothing is coming to mind, I understand the problem and desired to address it, but I don't know...  
… I could think of one way in JSON-LD how to do it, but not in this text approach..  
… Maybe Internationalization folks have an idea how this can be done.  

**Shigeya Suzuki:** I will talk to my friend to find out who is best to talk to.  

**Brent Zundel:** As you discover things, please add comments to the issue.  

**David Chadwick:** Work Human Colossus is doing on OCA could be a solution for this. They have tables with different tables to represent things. Table could also contain multiple images..  
… I think markus is familiar with this.  

**Markus Sabadello:** Little bit, but not enough to solve this.  

**David Chadwick:** I'll give you an email address of Human Colossus lead, you can chat to him directly. There are various presentations on Google, Youtube...  
… On ESSIF-Lab they did a demo a few weeks ago.  

> *David Chadwick:* paul.knowles@humancolossus.org for details of Overlays Capture Architecture (OCA) that should provide a solution to multi-lingual images.

> *Juan Caballero:* the oca repo is here: [https://github.com/the-human-colossus-foundation/oca-spec](https://github.com/the-human-colossus-foundation/oca-spec).

> *Juan Caballero:* they do some overlay/decorator stuff for mapping VC property names to new languages and char-sets.

> *Juan Caballero:* described here: [https://humancolossus.foundation/blog/cjzegoi58xgpfzwxyrqlroy48dihwz](https://humancolossus.foundation/blog/cjzegoi58xgpfzwxyrqlroy48dihwz).

</details>

**Comment by shigeya** [comment]
I've discussed with whom have some knowledge and got a suggestion. I will create a PR before next meeting (not today). I can't attend the meeting today.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-01-19-vcwg#section5-1) on 2022-01-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.1. Multilingual support for selecting a image file (issue vc-wg-charter#38)

_See github issue [vc-wg-charter#38](https://github.com/w3c/vc-wg-charter/issues/38)._




**Brent Zundel:** does anyone have anything more on this issue?.  
… still looking for a PR from shigeya.  

</details>

**Comment by shigeya** [comment]
I adjusted the text to target resources instead of strings.

Also gotten feedback on the relationship with [Developing Localizable Manifests](https://www.w3.org/TR/localizable-manifests/). There is a noticeable overlap, but there is a large gap between what we want to do in VC and what the Manifest work aims.

**Comment by shigeya** [comment]
I forgot to mention that this issue is related to #19 (closed). Please refer to it for examples and contexts.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-01-26-vcwg#section7-1) on 2022-01-26

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.1. Multilingual support for selecting a image file (issue vc-wg-charter#38)

_See github issue [vc-wg-charter#38](https://github.com/w3c/vc-wg-charter/issues/38)._




**Brent Zundel:** "Multilingual support for selecting a image file" Raised by Shigeya..  
… There is conversation in the PR.  

_See github pull request [vc-wg-charter#44](https://github.com/w3c/vc-wg-charter/pull/44)._




**Shigeya Suzuki:** The original markdown... not only the text but also the image file....  
… This PR and the last one, for multilingual text support, replacing strings....  
… to support both localized string and localized images..  
… I had some conversation... I hope she understands my intention....  
… Committed by some folks at Keio.  
… I'm still working with Kristina on some of these changes.  
… If she is satisfied with that, I'll create a PR.  

**Kristina Yasuda:** Are you suggesting to keep the original PR, or accepting the change request?.  

**Shigeya Suzuki:** I'm a bit confused about [your comment](https://github.com/w3c/vc-wg-charter/pull/44#issuecomment-1022484682) 2 hours ago.  
… The support for multilingual is not limited to ...?.  

> *Kristina Yasuda:* "Support for multilingual representations of resources not limited to the text strings that can be included by reference or by value".

**Brent Zundel:** Thank you both.  

</details>

**Comment by brentzundel** [comment]
Related PR has been merged, closing

**Comment by shigeya** [comment]
Thank you.
