### ISSUE TITLE
Standardizing JsonWebSignature2020 / JsonWebKey2020

### ISSUE THREAD

**Issue by OR13** [w3c/vc-wg-charter#45]
For the sake of interop with VC-JWT and JOSE more generally.

CCG work item: https://github.com/w3c-ccg/lds-jws2020/

Interop Test Suite: https://github.com/decentralized-identity/JWS-Test-Suite

This is a request to move the LD Suite in scope for the LD Integrity part of the next charter.

**Comment by selfissued** [comment]
This makes sense to me.

**Comment by mprorock** [comment]
full support from mesur.io for this

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-01-26-vcwg#section7-2) on 2022-01-26

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 7.2. Standardizing JsonWebSignature2020 / JsonWebKey2020 (issue vc-wg-charter#45)

_See github issue [vc-wg-charter#45](https://github.com/w3c/vc-wg-charter/issues/45)._




**Brent Zundel:** PR 45 raised by Orie. Orie, can you talk us through this?.  

**Orie Steele:** Sure. For those who don't know, in the VC Data Model 1.0 JSON-LD context, which are included and supported..  
… One is Ed25519, one is Secp256k1..  
… Both use detached JWS with algs from the JOSE registry.  
… Since the work ended, those are the only ones in the context..  
… This proposal would add support for all JWK key representations that could be used to verify verifiable credentials, as well as adding support for the JSON Web Signature 2020 signature type, which supports all those types..  
… This expression is a superset of what the VCDM already supports.  
… If we accept this, it will support RSA and NIST curves, as well as the already-supported Secp256k1 and Ed25519.  
… JWK is critical to VC Data Model.  

**Kyle Den Hartog:** Some considerations need to come into play. For that context, I think Manu agrees with this as well, is pulling things out of it, rather than adding to it..  

> *Orie Steele:* yep, +1 to not creating a single context..

**Kyle Den Hartog:** We've had conflicts with it. I don't think it leads to actionable changes in the charter..  
… More important: what we will face as interop problems.  
… I don't necessarily see it needs to be discussed in the charter.  
… But I could see it blocked if we are trying to support multiple signture types, JSON and Linked Data Integrity.  

> *Orie Steele:* The time to fix this IS at charter time :).

**Michael Jones:** I support Orie's points. Standardizing JWS-based signatures will improve interoperability quite a lot..  
… Those are based on existing IETF standards..  

> *Michael Prorock:* note PR [https://github.com/w3c/vc-wg-charter/pull/47](https://github.com/w3c/vc-wg-charter/pull/47).

**Michael Jones:** I hear Kyle about supporting 2 things, that that's already the case. Fully supporting JWS and the associated JWKs will improve interoperability with existing systems, not hinder it..  
… So I don't see that resulting in charter objections, I think it would result in charter support..  

**Orie Steele:** I agree about the context... I'm expecting this will be handled differently..  
… The job of the WG is to solve this..  
… The work items in the linked data integrity work stream are trying to define suites at charter time, to make it explicit what's in or out of scope..  

> *Michael Jones:* +1 that this should occur at charter time.

**Orie Steele:** This could result in some intention. We should bear the cost now, at charter time, to make things smoother moving forward..  
… Thanks.  

**Kyle Den Hartog:** I think it's actually quite useful for us to have these conversations. Personally, I believe having this JSON support is very beneficial. But since VCs and Linked data integrity has already been deployed....  
… If we can get it supported, great, but I don't see if it helps us get interoperability..  

> *Orie Steele:* I don't share your long term goal :) I believe suits should be defined... its not our job to tell folks which suites to use..

**Kyle Den Hartog:** Arguments can be made it's not that big a problem; it's probably resolvable in the charter. If we can do that, it may be useful..  
… So I'm in favor of having the conversation now, to see if we can figure it out early.  

</details>

**Comment by OR13** [comment]
I think we can close this issue, since the charter now lists this as a deliverable.
![Screen Shot 2022-02-14 at 11 15 12 AM](https://user-images.githubusercontent.com/8295856/153913188-678fbfc8-5797-485b-aaea-25bafc5c3440.png)
