### ISSUE TITLE
Data Integrity Crypto Suite Registry

### ISSUE THREAD

**Issue by OR13** [w3c/vc-wg-charter#62]
Closest thing we have today is: https://w3c-ccg.github.io/ld-cryptosuite-registry/

If the WG will be defining suites (currently that is the plan).

Where will they be registered? 

Who maintains the registry?

Do we handle this the same as DID Spec Registries?

Can we expect formal objections to taking a "big tent" / "inclusive" or "decentralized" approach to crypto suites.

I think we need clarity on this before major sections of the charter will make sense to folks who have been following the work.

**Comment by jandrieu** [comment]
Can someone clarify the question here?

I had a collaborator ask if they should be concerned about what they fear might be an "allow-list" approach to cryptosuites for VC conformance, rather than the current model for open extensibility that allows any cryptosuite to be used.

I get that there is an interest in the VCWG defining suites, but I must have missed the proposal (if there was one) that would require the use of specific suites for conformance.     

Is there such a proposal?

**Comment by OR13** [comment]
@jandrieu yes, basically the current charter mentions a number of crypto suites... and implies that some will be "normatively defined" and others won't be.

The purpose of this issue is to gather support for acknowledging that this list will contain many entries.

I should also note that this list seems to only apply to "Linked Data Integrity" items... JWS / VC-JWT is not dependent on these items.

In other words, there is an implied "allow list" for JWT... and there is an implied "allow list" for LD Proofs... and both come from the idea that only "registered things should be allowed"...

I think it is 100% a mistake to attempt to use the normatively defined suites as some kind of "allow list"... we did that in v1 and it really wrecked the ability to add extensions, and make the v1 context a mess.

VC-JWT didn't have that issue, and it was easier to add support for secp256k1 after the work item ended.

Hopefully this helps some, but to be honest I think we are still trying to gather consensus on how best to address these issues, it has been suggested that maybe we should only discuss 1 or 2 suites in the WG... I am advocating for only defining 1 or 2 normatively, and establishing a registry so that work can progress independent of the working group.

**Comment by selfissued** [comment]
To the extent that we specify things that should be registered because they're an instance of a category that is likely to be extended, then a registry is the appropriate mechanism.

**Comment by jandrieu** [comment]
I'd argue that the W3C is not currently capable of managing registries effectively.

What we are seeing with the DID Specification Registries is a case in point. It wasn't until Daniel Hardman and I (in support of the DID Method Rubric) made the explicit request did we even ask spec submitters for contact information. Those details immediately got co-opted for authentication for change control, without discussion. The result is a lack of specificity about how registry entries are maintained and even what the data currently in the registry means wrt ownership, authentication, and authorizations. This has caused a kerfuffle with did:keri, which exposed the lack of institutional sensibility about maintaining a registry.

Repeating that situation with VCs seems like a mistake.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-02-02-vcwg#section5-1) on 2022-02-02

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.1. Data Integrity Crypto Suite Registry (issue vc-wg-charter#62)

_See github issue [vc-wg-charter#62](https://github.com/w3c/vc-wg-charter/issues/62)._




**Orie Steele:** As you all know, the VC Data Model 1.0 shipped a bunch of term definitions in it's v1 context w/ cryptosuite proofs and everyone has experienced how painful and bad of an idea that was..  
… I think we know that we want the v2 context to not do that, and we want to allow people to build cryptosuites, some of which leverage new crypto, some that might be owned by CGs, some by open source software, we don't know where cryptosuites are going to be built, we know not all are going to be normatively defined, we need some way of addressing that and being respectful where work is happening..  
… In DID Core, we had a DID Spec Registries and it acknowledged both normative properties and extension properties. It's not a perfect solution, but it does account for this desire to do work in CGs and register it, but not have it impact the core specifications..  
… I think it can address issues that mike jones and davidc discussed..  

**Kyle Den Hartog:** Registries are in scope and so question is -- do we need to further define what scope means, can we leave it to WG?.  

**Manu Sporny:** +1 to Orie's framing of the concern and the potential solution. As Kyle also said, registries are in scope. I think people should just look at the language in the current charter and propose new language in a PR. I think this work you mentioned, Orie, is already in scope..  
… Please take a look at the language and raise a PR if you think it needs refining. I currently think it's adequate..  
… I do think it should be left up to the WG -- it would be terrible if the charter didn't allow us to be responsive to work done in the WG..  

**Dave Longley:** +1 to leaving it up to the WG.  

**Brent Zundel:** All comments we made will be put into issue, any other comments before moving forward?.  

> *Michael Prorock:* +1 to leaving up to WG.

**Orie Steele:** There was a question in chat for IANA registries? We've talked about this a lot here -- for VC-JWT, we should point to IANA (we shouldn't duplicate/replace them for JWT).  

**Manu Sporny:** +1 to that.  

> *David Chadwick:* +1.

> *Orie Steele:* I think the current language needs work..

**Dave Longley:** +1 to not duplicate or replace existing registries that work, +1 for letting the WG figure out what registries are needed.  

**Justin Richer:** Another data point for cryptographic algorithm registry -- HTTP Signatures work, it also has its registry of algorithms, but also has explicit instructions when people want to use JWA and how those apply. For cryptographic algorithms, same approach could be applied here..  

> *Orie Steele:* +1 justin.

**Michael Jones:** To the extent that we're specifying things that are a category, they should be in registries. If there is an existing IANA registry, we should reuse it. If it's a new kind of thing, we should run a registry like DID Spec Registries..  
… I'd be glad to help work on that..  

> *Michael Prorock:* +1 - well stated mike jones.

**Manu Sporny:** +1 to what selfissued just said.  

</details>

**Comment by brentzundel** [comment]
@OR13 do you agree that #85 will address this issue?

**Comment by brentzundel** [comment]
The associated PRs which reflect the consensus of the group (and lack thereof) have been either merged or closed. Closing this Issue.
