### ISSUE TITLE
Some of the "other deliverables" raise patent concerns

### ISSUE THREAD

**Issue by jyasskin** [w3c/vc-wg-charter#72]
https://w3c.github.io/vc-wg-charter/#ig-other-deliverables currently says:

> Other non-normative documents may be created such as:
> 
> - Presentation Request Data Model
> - Storage and Sharing of Verifiable Credentials
> - Privacy Guidance for Verifiable Credentials
> - An API for Verifiable Credential Exchange
> - Guidance to enhance verifiable credential interoperability: …
> - Test suites for verifiable credential proof types: …
> - Extensions for binding multilingual strings to [GNU gettext](https://www.gnu.org/software/gettext/)-like localization files

Some of these, especially the API and sharing descriptions, are potentially patentable. If the group works on these as [Notes](https://www.w3.org/2021/Process-20211102/#Note), "The W3C Patent Policy does not apply any licensing requirements or commitments for Notes or Draft Notes." Keeping these in the Credentials Community Group would keep them under the [Community CLA](https://www.w3.org/community/about/process/cla/), which does create a patent license for contributions, so that implementers won't be surprised after they've relied on a contribution.

Note that I'm far from an expert on patent concerns and defer to the W3C's legal team on this topic.

**Comment by nadalin** [comment]
There is a copyright policy assigned to W3C notes that you have to be aware of.

**Comment by brentzundel** [comment]
I believe that possible resolution of this issue is underway in the discussion on PR #77.

**Comment by kdenhartog** [comment]
+1 I think the restructuring towards Web App style charter that originally @jyasskin pointed to should make it much easier to align with these concerns to avoid patent issues. We'll probably need a few follow on PRs in order to move some input documents to the right location, but I believe this concern will be addressed in subsequent PRs.

Thank you for pointing this out that notes will not help us when it comes to patent protection.

**Comment by brentzundel** [comment]
@jyasskin there have been significant changes to the charter since this issue was raised.
Are there further changes you believe need to be made, or has this issue been addressed?

**Comment by jyasskin** [comment]
I'm still concerned that a couple of the envisioned WG Notes are likely to include patentable material, which wouldn't be protected unless they're also in CG reports. 

* Presentation Request Data Model
* Storage and Sharing of Verifiable Credentials
* One or more HTTP protocol definitions for Verifiable Credential Exchange (such as the [VC-API](https://w3c-ccg.github.io/vc-api/))
* Guidance on Verifiable Credential Exchange over [OpenID Connect](https://openid.net/specs/openid-connect-core-1_0.html)
* Verifiable Credential Exchange over [Grant Negotiation and Authorization Protocol (GNAP)](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol)

It sounds like some WG members do think it's valuable to publish these documents concurrently as both CG reports and WG notes, which would avoid the patent problem, but seems like unnecessary work to me. I think @kdenhartog was thinking that it'd make sense to move some of these items to the new Conditional Normative Specifications section, which I think would solve the problem more cleanly.

I don't think this concern would be a reason to object to the charter, just something y'all might want to reconsider. Feel free to close if you have considered it. :)

**Comment by kdenhartog** [comment]
> I think @kdenhartog was thinking that it'd make sense to move some of these items to the new Conditional Normative Specifications section, which I think would solve the problem more cleanly.

Correct that was my thinking and I believe it's the cleanest solution to this problem long term because we're ending up with more normatively defined documents as well to build on. The obvious tradeoff is that we may end up with quite a few REC track documents that need to be authored and edited.

**Comment by brentzundel** [comment]
closing, based on meeting conversation

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-03-23-vcwg#section2-3) on 2022-03-23

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.3. Some of the "other deliverables" raise patent concerns (issue vc-wg-charter#72)

_See github issue [vc-wg-charter#72](https://github.com/w3c/vc-wg-charter/issues/72)._




**Brent Zundel:** This led to a good conversation about IPR for notes versus specifications..  
… I do not believe this should be a blocker for the charter..  
… Should any potential notes be removed?.  
… If so, who is going to do it?.  

**Manu Sporny:** We've hit a steady state and shouldn't rock the boat..  
… We have multiple mechanisms for patent protection..  
… Should we ask Wendy or Rigo what mechanisms are available to us for patent protection of the note?.  
… For instance, could companies get together and submit the note as a member submission? (Not that I think this is a good idea.).  

**Orie Steele:** This is related to the issues around licenses..  
… I'm not sure how to safely ask this question..  
… There have been concerns about what happens to the W3C if the legal entity issue is not resolved..  

**Ivan Herman:** Let's not go there..  

**Orie Steele:** Does anyone with more experience think this is relevant to the topic at hand?.  

**Ivan Herman:** Wendy is the right person to ask.  
… This is the first time I've hit this issue in any working group..  
… There is a remote possibility of the W3C finding itself in a strange spot..  
… If that happens, there will be a W3c-wide line of actions to take..  
… We do not need to do anything special in this working group..  
… We are using the most liberal license already..  

> *Manu Sporny:* Reminder that all of our specs are published under a permissive license: [https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document).

> *Manu Sporny:* also, +1 to what ivan is saying and what brentz is about to say. :).

> *Orie Steele:* good, as long as we have already picked the most permissive, thats all we can do..

**Brent Zundel:** The licenses we've already used for the VC Data Model are already the most permissive ones..  
… Worst comes to worst, the documents could move to another organization..  
… With nothing more to be said about this issue, I'm going to close it..  

> *Manu Sporny:* You can fork the spec today, if you wanted to -- I mean, you'd be shunned, SHUNNNNNNnnnnED... but you could do it. :).

</details>
