### ISSUE TITLE
This should be LEVEL 2 not VERSION 2

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-wg-charter#81]
W3C updates go by LEVEL, if this is truly an update to the previous VC specification this should be LEVEL 2 and called out in the charter.

**Comment by iherman** [comment]
There is no such hard rule at W3C, @nadalin (maybe there should be, but that is another discussion). Working groups have the freedom to use other terminology like "version". There are several examples; see, for example, the [EPUB WG Charter](https://www.w3.org/2020/12/epub3-wg-charter.html) (where I am also active) which uses the term "version" all over the place.

**Comment by OR13** [comment]
Suggest we close the issue in absence of a citation.

Breaking changes implies a version change to me.

**Comment by peacekeeper** [comment]
I think "level 2" sounds like it's a superset or an additional layer on top of "level 1", which would be confusing. So "version" seems like a better term.

**Comment by nadalin** [comment]
This brings up the question of version 2 supercedes Verizon 1 or are both still viable. Level seems a better term, that could be why W3C recommends that term.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by iherman** [comment]
> This brings up the question of version 2 supercedes Verizon 1 or are both still viable. Level seems a better term, that could be why W3C recommends that term. 

W3C does not "recommend" that term. WG-s choose (or not) that term or use a different one. It is the prerogative of a WG.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-03-02-vcwg#section5-2) on 2022-03-02

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.2. This should be LEVEL 2 not VERSION 2 (issue vc-wg-charter#81)

_See github issue [vc-wg-charter#81](https://github.com/w3c/vc-wg-charter/issues/81)._




**Brent Zundel:** next issue #81.  
… rather than v2, perhaps we should call it level 2 to comply with other W3C recommendations.  

**Manu Sporny:** there's no rule in here that says use level 2 instead of version 2. It is confusing.  

> *Joe Andrieu:* -1 on this issue.

**Joe Andrieu:** Level 2 to me, implied semantics, seems to me that Level 1 is still valid. It doesn't convey we're "updating that first version to newer version, where not all of the first thing might be valid anymore.".  

> *Juan Caballero:* "An earlier version of EPUB (EPUB 3.0.1) was published as an ISO standard ISO/IEC TS 30135:2014 (parts 1-7). This Working Group and ISO may consider updating that ISO specification once the new Recommendations are published..."
> Additionally, there are currently activities within ISO/IEC JTC 001/SC34 on specifications that rely on earlier versions
> of EPUB (e.g., EPUB Preservation, EPUB Accessibility). A liaison has to be maintained on, possibly, updating those ISO specifications to the latest versions of EPUB 3, specified by this Working Group."

> *Juan Caballero:* (^from Iván's example).

</details>

**Comment by nadalin** [comment]
I find use of version very confusing not knowing if version 2 supercedes or both versions are valid. Whatever naming is used. It needs to be clarified on the intent on this next version or level.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Sakurann** [comment]
We added a following text to the charter to clarify that version 2 supersedes version 1:

> It is explicitly not a requirement that the new specifications be fully compatible with related past specifications.

Would this be acceptable?

**Comment by nadalin** [comment]
LGTM

**Comment by brentzundel** [comment]
closing, based on discussion in the group meeting

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-03-16-vcwg#section4-1) on 2022-03-16

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.1. This should be LEVEL 2 not VERSION 2 (issue vc-wg-charter#81)

_See github issue [vc-wg-charter#81](https://github.com/w3c/vc-wg-charter/issues/81)._




**Kristina Yasuda:** I think it turned out that Tony's concern was that version 2 allows breaking changes to version 1. That it supersedes version 1 and we already have that in the charter and he's ok with that language.  
… So we can close that issue.  

**Manu Sporny:** That does not mean that our intent is to completely break VCs. There should be an expectation that any backwards compatible or breaking change will undo significant scrutiny.  

> *Michael Prorock:* +1 manu - avoiding breaking changes if possible.

**Kristina Yasuda:** I think the clarification here is that we will tell people to look at version 2 once published.  

**Manu Sporny:** Correct.  

**Kristina Yasuda:** Yes, and we aren't actively trying to break version 1 if we can avoid it.  

</details>
