### ISSUE TITLE
New PR needed if did:key/multibase is going to be in scope

### ISSUE THREAD

**Issue by bumblefudge** [w3c/vc-wg-charter#83]
feel free to assign me, Orie suggested closing #51 and starting over, which I plan to do next week before or after wednesday's meeting.

**Comment by brentzundel** [comment]
there is nothing in the current text of the charter that would prohibit did:key/multibase from being in scope for the new WG. There are already deliverables with input documents that refer to these things.

It is not clear to me what changes are needed in the charter to support this. I recommend closing.

**Comment by msporny** [comment]
@bumblefudge wrote:
> It is not clear to me what changes are needed in the charter to support this. I recommend closing.

Agree, specifically @bumblefudge the definition of Multikey exists in the Data Integrity specification (which is an input document):

https://w3c-ccg.github.io/data-integrity-spec/#multikey

What do you feel is missing in the current charter?

**Comment by quartzjer** [comment]
Could this issue be combined with #97 as they seem to me to be discussing the same thing?

**Comment by kdenhartog** [comment]
> Could this issue be combined with #97 as they seem to me to be discussing the same thing?

+1 I've added some details to frame #97 better so that this issue can be closed and discussion can be consolidated over there.

**Comment by brentzundel** [comment]
closing based on meeting conversation

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-03-23-vcwg#section2-7) on 2022-03-23

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.7. New PR needed if did:key/multibase is going to be in scope (issue vc-wg-charter#83)

_See github issue [vc-wg-charter#83](https://github.com/w3c/vc-wg-charter/issues/83)._




**Brent Zundel:** New PR needed if [did:key/multibase](did:key/multibase) is going to be in scope.  

**Manu Sporny:** I think this is already covered by the charter.  
… The WG can decide whether multikey should go to recommendation.  

> *Manu Sporny:* In other words, this is clearly in scope and the VC2WG can discuss whether or not they want to make this a REC..

**Brent Zundel:** Any other comments on this before I close it on the basis that no changes are required in the charter?.  
… We are at our final issue.  

</details>
