### ISSUE TITLE
rename a deliverable to "Verifiable Credential Proofs of Integrity 1.0"

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-wg-charter#87]
Suggest we rename a deliverable "Verifiable Credential Data Integrity 1.0" to "Verifiable Credential Proofs of Integrity 1.0"? It is very confusing that a current CCG document called "Data Integrity 1.0" is one of the documents in a family of specifications called "Verifiable Credential Data Integrity 1.0".

**Comment by OR13** [comment]
I don't find the suggested change helpful.

Can you provide additional context?

Maybe relate this to JWTs so we can see why you think the name change is helpful.

This the way I see it.

1. VCDM 2.0 a JSON Data Model for Credentials
2. Verifiable Credential Data Integrity 1.0 - > VC-LD, VC-JWT

If you are trying to say "Data Integrity 1.0" implies "LD Only"... yea, i kinda agree with that.

I think a more natural grouping would be:

1. VCDM 2.0 a JSON Data Model for Credentials
2. VC-JWT
3. VC-LD

**Comment by brentzundel** [comment]
I personally prefer `data integrity` over `proofs of integrity`, but would also not be opposed to this change.

I would also like to note that the name the next WG chooses to give to its normative deliverables does not necessarily need to be exactly the name as listed in the charter.

**Comment by msporny** [comment]
> I don't find the suggested change helpful.

Agree, -1 to the change. I think it's coming from a place where there isn't an understanding of the history of how we ended up here and I'm concerned with moving forward with a change for the wrong reasons.

> If you are trying to say "Data Integrity 1.0" implies "LD Only"... yea, i kinda agree with that.

Sorry, no, we specifically changed the name from "Linked Data Proofs/Signatures" to "Data Integrity" because you can use the Data Integrity specification to canonicalize and sign w/o using Linked Data anything (e.g., JCS + JwsBasedSignature). Data Integrity is a container format (really, an object annotation format that allows you to hang a `proof` value off of the object). That is, it is "a generalized way of protecting a credential". Really, it's a generalized mechanism for protecting any sort of object, we just happen to be focused on Verifiable Credentials in this WG.

There are three potential paths for protecting a credential:

* VC-JWT - a envelope-based format for protecting VCs using digital signatures.
* VC-JWP - a envelope-based format for protecting a VC using proofs (but not really, it's really about selective disclosure).
* VC-DI - an annotation-based format for protecting a VC using proofs, of which digital signatures can be one form of proof.

So, -1 to changing the names above at this point in time.

I wouldn't be opposed to something like: "Securing Verifiable Credentials 1.0" or "Protecting Verifiable Credentials 1.0" -- and then list all the "container formats" and cryptosuites that we plan to work on to do so.

**Comment by Sakurann** [comment]
> "Securing Verifiable Credentials 1.0" or "Protecting Verifiable Credentials 1.0"
Sounds good.

**Comment by quartzjer** [comment]
@msporny 
> VC-JWP - a envelope-based format for protecting a VC using proofs (but not really, it's really about selective disclosure).

Just FYI, unlinkability is equally important as selective disclosure, and ZKPs are essential for that.

**Comment by brentzundel** [comment]
The associated PRs which reflects the consensus of the group has been merged. Closing this Issue.
