### ISSUE TITLE
Environmental, Ethical and Social Implications of the Work

### ISSUE THREAD

**Issue by OR13** [w3c/vc-wg-charter#89]
Since W3C members have formally objected to specifications that fail to address these concerns perviously, we should seek to address them preemptively, and the charter should authorize / endorse our ability to comment on them.

In particular issues such as loss of service from malicious issuers / governments.

The energy consumption associated with some cryptographic operations such as zkSnarks - https://eprint.iacr.org/2019/550.pdf

The social implications of a "papers please" culture... we've seen tensions from digital vaccination, etc.

Let's make sure that we agree how we will or will not address these concerns before the work starts.

**Comment by brentzundel** [comment]
It seems that the best way to address such concerns would be via non-normative deliverables. Since the set of non-normative deliverables in the charter is a non-exhaustive set of potential deliverables, the WG is not the least prohibited from producing non-normative content for this purpose.

Do you feel the benefit of explicitly listing in the charter these additional non-normative deliverables outweighs the drawbacks of having a much longer non-normative deliverables section?

It seems that it may be better to open an issue at https://github.com/w3c/vc-data-model/issues to make sure the next WG addresses these concerns than to further encumber the charter.

**Comment by jandrieu** [comment]
I think this question is a continuation of a mistake the W3C began with the EWPs themselves.

Trying to be a nanny-state moralizing force--which directs technologies towards some notion of "good" is inappropriate in a global standards making body.

Every attempt to impose global morality will fail, precisely because we all have good reasons for having different values. Picking and choosing particular language to advocate or attack particular concepts becomes a game of both whack-a-mole and selective attacks. 

**Whack-a-mole** because there will always be uses of technology that offend someone. You can't mitigate the unfortunate use of technology by restrictions at the technology layer. Like all moral and ethical questions, it is our social, political, and religious institutions that address morality and ethics and their intersection with society. Advocating for the VC WG or the W3C to become an arbiter of Environmental, Ethical, and Social good is to place the moral authority of the W3C over that of nation-states, regional organizations, private enterprises, and individuals.

This form of creeping centralization is anathema to this entire ecosystem of work. 

**Selective attacks** are a problem because this notion of Env/Eth/Soc Implications creates a literal attack surface that any motivated "do gooder" could use to attack otherwise fine solutions. We saw this with the unfounded environmental objections to the DID Core spec. That was a HUGE distraction to our efforts and a HUGE drain on our collective resources to move this work forward.

It would be a huge mistake to foster these kinds of attacks by creating ANY points of attachment for such baseless, biased interference with our work. Rather, we should create tools like the DID Method Rubric that allow us to redirect these attacks to productive discourse.

IMO, the right way to handle the potential consequences of our work is to understand and document the tradeoffs of any potential decision, and allow policy makers and individuals to make their own decisions. It's not the W3C's place to tell China how to manage its credentials or identifiers, nor to demand that any particular technology be legalized by China. Nor should we direct the Vatican about what it or Catholics should be allowed to do. It's a gross layer violation of the highest order. That is what these types of restrictions imply: that the W3C's sense of ethics and morality should trump the ability for appropriate decision makers to make their own decisions.

If we care at all about decentralization, we should prevent, rather than enable, a minority group's notion of "good" to be weaponized by a centralized player to police the world.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-03-02-vcwg#section5-4) on 2022-03-02

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.4. Environmental, Ethical and Social Implications of the Work (issue vc-wg-charter#89)

_See github issue [vc-wg-charter#89](https://github.com/w3c/vc-wg-charter/issues/89)._




**Brent Zundel:** issue #89.  

**Orie Steele:** the tech we are working on here has ethical consequences, from expensive processes to digital human rights like freedom of movement, which can be impacted by adoption of VCs at scale.  
… what I don't want to do is get to the end of the process and have people oppose it then.  

**Manu Sporny:** I'm concerned that this is like a honey pot for endless discussions of ramifications of technology.  
… I would be fine to say we are going to publish a note.  

**Manu Sporny:** that note can be a centralized focus for those interested. but if we start taking up main call time, that would be a negative.  

> *Orie Steele:* previously a "note" was no sufficient to avoid FOs..

**Joe Andrieu:** I'm pretty opposed to this approach at all, it's creeping Nanny-state-ism. People will use it to attack things they don't like. That's not our role here. Our role is to step outside the "morality matrix". Our job is to put options on the table..  
… If we need to start the fight here, the EWP work is a mistake. That whole framework that the W3C should be the morality police is misguided. I don't think this is the right way to handle these problems..  

---

</details>

**Comment by msporny** [comment]
W3C TAG just did something related to this: https://github.com/w3ctag/ethical-web-principles/pull/72

**Comment by OR13** [comment]
The group has opted not to take any additional steps to mitigate the risks associated with FOs related to these topics, the WG will retain the ability address these concerns one a case by case basis.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2022-03-23-vcwg#section2-2) on 2022-03-23

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.2. Environmental, Ethical and Social Implications of the Work (issue vc-wg-charter#89)

_See github issue [vc-wg-charter#89](https://github.com/w3c/vc-wg-charter/issues/89)._




**Orie Steele:** Objections to the DID spec included social and environmental issues..  
… The TAG seems to be taking us in a direction to require environmental statements, etc..  
… There's a cultural shift to acknowledge the implications of the work that we do..  
… I want us to explicitly decide whether to add this to the charter or not..  
… ZKPs are notoriously expensive in terms of computation..  
… New ZKP cryptography is expensive.  
… New ZKP is subject to attacks, etc..  
… I want to have the conversation at the start while chartering, rather than at the end when we can't fix it..  

**Ivan Herman:** We don't know yet how this discussion will evolve at the W3C..  
… I would be very concerned about putting anything specific into the charter..  

> *Brent Zundel:* +1 Ivan.

> *Dave Longley:* +1 to ivan.

**Ivan Herman:** Like internationalization, we may have to deal with it in any case..  
… I don't see what might need to change..  

> *Michael Jones:* +1 to Ivan.

> *Manu Sporny:* +1 to close and deal w/ it when something concrete happens..

**Orie Steele:** I have not closed the issue..  
… I will leave a comment and then close the issue..  
… I remain concerned about the W3C's ability to address objections of this nature..  

</details>

**Comment by rxgrant** [comment]
I agree with @jandrieu that the W3C has bitten off more than it can chew with FOs based on EWP, and we should not encourage them by presuming to accept the frame.  

The Internet is supposed to be a place where people can define themselves and engage with others.  The proposed EWP are incoherent in that they are self-contradicting because they are not ranked.  Freedom is not important in that list.  (When freedom isn't important, you don't need any cryptography at all - look at all the cycles you can save!)  Instead, the list is being used to reject technologies that use trivial additional energy over existing infrastructure.  It's completely tragic and will result in (more) stupid fights until EWP is pared back.
